
plugins {
    id("java")
}

group = "Cloveri.Start"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
    maven {
        url = uri("https://company/com/maven2")
    }
    google()
    gradlePluginPortal()
}

dependencies {
    implementation 'com.github.javafaker:javafaker:1.0.2'
    testImplementation(platform("org.junit:junit-bom:5.10.0"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testImplementation "org.junit.jupiter:junit-jupiter-api:5.9.2"
    testImplementation 'io.github.bonigarcia:webdrivermanager:6.1.0'
    testImplementation 'com.codeborne:selenide:6.19.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.9.2'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'

    testImplementation 'io.qameta.allure:allure-selenide:2.20.1'
    testImplementation 'io.qameta.allure:allure-junit5:2.18.1'
    testCompileOnly 'org.projectlombok:lombok:1.18.30'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.30'
}

compileJava {
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()

    // Указываем кодировку для JVM
    systemProperty 'file.encoding', 'UTF-8'
    systemProperty 'sun.jnu.encoding', 'UTF-8'
    systemProperty 'sun.stdout.encoding', 'UTF-8'  // кодировка stdout
    systemProperty 'sun.stderr.encoding', 'UTF-8'  // кодировка stderr
    //systemProperty 'chrome.binary', 'C:/ProgramFiles64Folder/chrome-win64/chrome.exe'

    // в тестах, вызывая `gradlew test -Dselenide.headless=true` будем передавать этот параметр в JVM (где его подтянет Selenide)
    // свойство selenide.headless используется в проектах на основе Selenide для передачи значения параметра в JVM
    // systemProperty 'selenide.headless', System.getProperty('selenide.headless')
    // свойство chromeoptions.prefs используется для задания настроек браузера в проектах на основе Selenide, выключаем менеджер паролей
    systemProperty 'chromeoptions.prefs', System.getProperty('chromeoptions.prefs', "profile.password_manager_leak_detection=false")
    // Включаем headless-режим для Selenide
    //systemProperty 'selenide.headless', 'true'
    // Настройки Chrome для headless-режима
//    systemProperty 'chrome.switches', [
//            '--headless',
//            '--no-sandbox',
//            '--disable-dev-shm-usage',
//            '--disable-gpu',
//            '--window-size=1920,1080'
//    ].join(',')
}